# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 19:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='ActivityBluePrint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=10)),
                ('caption', models.CharField(blank=True, max_length=50)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpmapp.Action')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpmapp.Activity')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Businesses',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=1000)),
                ('date_submitted', models.DateTimeField()),
                ('user_submitted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FlowBluePrint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessBluePrint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('desc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProdLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('desc', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Statuses',
            },
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('flowblueprint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bpmapp.FlowBluePrint')),
            ],
            bases=('bpmapp.flowblueprint', models.Model),
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('processblueprint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bpmapp.ProcessBluePrint')),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('date_created', models.DateTimeField()),
                ('notes', models.TextField(max_length=500)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpmapp.Business')),
                ('prodline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpmapp.ProdLine')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpmapp.Project')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpmapp.Status')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpmapp.ProcessType')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Processes',
            },
            bases=('bpmapp.processblueprint', models.Model),
        ),
        migrations.AddField(
            model_name='flowblueprint',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='bpmapp.ActivityBluePrint'),
        ),
        migrations.AddField(
            model_name='flowblueprint',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='bpmapp.ActivityBluePrint'),
        ),
        migrations.AddField(
            model_name='flowblueprint',
            name='process_Blueprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpmapp.ProcessBluePrint'),
        ),
        migrations.AddField(
            model_name='activityblueprint',
            name='process_BluePrint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpmapp.ProcessBluePrint'),
        ),
    ]
