# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 01:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpmapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityblueprint',
            old_name='process_BluePrint',
            new_name='process_bluePrint',
        ),
        migrations.RenameField(
            model_name='flowblueprint',
            old_name='process_Blueprint',
            new_name='process_blueprint',
        ),
    ]
